# /resources/k8s/pod1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox:1.31.0
    command: ["/bin/sh", "-c", "touch /tmp/ready && sleep 1d"]
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 10